name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'

      - name: Install Playwright browsers with dependencies
        run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"

      - name: Build with Maven
        run: mvn -B --no-transfer-progress clean install

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: structurizr-confluence-jars
          path: |
            target/structurizr-confluence-*.jar
            target/quarkus-app/**

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (validate only)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: structurizr-confluence:ci
