name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24-dind
        options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'

      - name: Verify Java version
        run: |
          java -version
          mvn -version
          echo "JAVA_HOME: $JAVA_HOME"

      - name: Install Playwright browsers with dependencies
        run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"

      - name: Setup Docker for Testcontainers
        run: |
          # Set Docker socket permissions for testcontainers
          sudo chmod 666 /var/run/docker.sock
          # Wait for Docker daemon
          docker info

      - name: Build with Maven
        run: mvn -B --no-transfer-progress clean install
        env:
          # Enable Docker access for tests
          TESTCONTAINERS_RYUK_DISABLED: true

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: structurizr-confluence-jars
          path: |
            target/structurizr-confluence-*.jar
            target/quarkus-app/**

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (validate only)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: structurizr-confluence:ci
